# Generated by Django 4.2.23 on 2025-06-29 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente_nombre", models.CharField(max_length=255)),
                ("direccion", models.CharField(max_length=255)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "forma_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("debito", "Débito"),
                            ("credito", "Crédito"),
                            ("transferencia", "Transferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_ruta", "En ruta"),
                            ("entregado", "Entregado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "chofer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
                (
                    "tipo_cilindro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.cylindertype",
                    ),
                ),
            ],
        ),
    ]
